- name: A10 class-list import example
  connection: local
  hosts: localhost
  tasks:
  - name: Import class-list file
    a10_import:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      class_list: "class_list_filename"
      remote_url: "scp://username:password@host:/path/to/file"
