- name: A10 export aflex example 
  connection: local
  hosts: localhost
  tasks:
  - name: Export aflex files 
    a10_export:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      aflex: "aflex_scirpt_name"
      remote_url: "scp://username:password@host:/path/to/file"
