- name: Create a10_slb_server example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_server instance
    a10_slb_server:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: server1
      host: 10.0.0.1
      action: enable
      template_server: default
      conn_limit: 1
      weight: 1
      stats_data_action: stats-data-enable
